# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LevelUpUp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LevelUpUp

  target 'LevelUpUpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LevelUpUpUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDWebImage', '~> 3.7.5'
pod 'MJRefresh', '~> 3.1.0'
pod 'RegexKitLite', '~> 4.0'
pod 'IQKeyboardManager', '~> 3.3.5'
pod 'Masonry'
pod 'FMDB'
pod 'UMengAnalytics-NO-IDFA'
#pod 'Charts’, ’~> 3.0.1’

end
